---
name: Test issue

on:
  issues:
    types: [closed]
jobs:
  show-data:
    if: github.event.issue.state_reason == 'completed'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: print data
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"
          echo "Issue: ${{ github.event.issue.state }}"
          echo "Issue: ${{ github.event.issue.state_reason }}"
      - name: dump description
        run: |
          echo "${{ github.event.issue.body }}" > issue_description.md
      - name: print metadata
        run: |
          echo issue_description.md
