---
name: Information printer

on:
  push:
    tags: ['v*']
  release:
    types: [published]
jobs:
  show-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: print data
        run: |
          echo "${GITHUB_REF}"
          echo "${GITHUB_REPOSITORY}"
      - name: trying subaction
        uses: yashpatel6/test-actions/add-asset@v2.0.7
        with: 
          repository-to-tar: ${GITHUB_REPOSITORY}
          tag-to-checkout: ${GITHUB_REF}
