---
name: Publish Docker image

on:
  push:
    tags: ['v*']
  release:
    types: [published]
jobs:
  show-data:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: print data
        run: |
          echo "${{ github }}"
