---
name: test-workflow

on: push
env:
  ENV_FILE: metadata.yaml
jobs:
  load-variables:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run read-yaml action
        id: yaml-data
        uses: KJ002/read-yaml@main      # You may wish to replace main with a version tag such as '1.6' etc.
        with:
          file: './metadata.yaml'          # File to read from
          key-path: '["Image_Name"]'
      - name: Display read-yaml output
        run: echo "${{ steps.yaml-data.outputs.data }}"
      - name: trycat
        run: cat ${{ env.ENV_FILE }} >> $GITHUB_ENV
      - name: printer
        run: echo "${{ env }}"
